export const ADDPRODUCT = "ADDPRODUCT";
export const GETPRODUCTS = "GETPRODUCTS";
export const EDITPRODUCT = "EDITPRODUCT";
export const SETPRODUCT = "SETPRODUCT";
export const DELETEPRODUCT = "DELETEPRODUCT";